report:
  enabled: false
  output_dir: reports

profiles:
  default:
    solver_name: appsi_highs
    tee: false
    options: {}
  optimal:
    solver_name: appsi_highs
    tee: false
    options:
      mip_rel_gap: 0.0
  faster_not_optimal:
    solver_name: appsi_highs
    tee: false
    options:
      time_limit: 10
      mip_rel_gap: 0.05
